# Generated by Django 4.1 on 2022-10-29 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_1', '0005_alter_register1_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Note', models.TextField()),
                ('Save_Date', models.DateTimeField(auto_now_add=True)),
                ('Last_Date', models.DateTimeField()),
                ('Status', models.BooleanField()),
                ('Count', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
