# Generated by Django 4.1 on 2022-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_1', '0007_alter_register1_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
